# Generated by Django 4.0.2 on 2022-03-12 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('seo_url', models.CharField(max_length=255, unique=True)),
                ('short_details', models.CharField(blank=True, max_length=800)),
                ('full_details', models.TextField(blank=True)),
                ('category_icon', models.ImageField(blank=True, upload_to='upload/category/icon/')),
                ('category_image', models.ImageField(blank=True, upload_to='upload/category/image/')),
                ('category_cover_image', models.ImageField(blank=True, upload_to='upload/category/cover_image/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebSite',
            fields=[
                ('site_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('seo_url', models.CharField(max_length=255, unique=True)),
                ('short_details', models.CharField(blank=True, max_length=800)),
                ('full_details', models.TextField(blank=True)),
                ('site_icon', models.ImageField(blank=True, upload_to='upload/sites/icon/')),
                ('site_logo', models.ImageField(blank=True, upload_to='upload/sites/logo/')),
                ('site_image', models.ImageField(blank=True, upload_to='upload/sites/image/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_1', models.CharField(blank=True, max_length=12)),
                ('mobile_2', models.CharField(blank=True, max_length=12)),
                ('mobile_3', models.CharField(blank=True, max_length=12)),
                ('email_1', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_2', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_3', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True)),
                ('pincode', models.CharField(blank=True, max_length=8)),
                ('image', models.ImageField(blank=True, upload_to='upload/sites/header_logo/')),
                ('header_logo', models.ImageField(blank=True, upload_to='upload/sites/header_logo/')),
                ('footer_logo', models.ImageField(blank=True, upload_to='upload/sites/footer_logo/')),
                ('orther_logo', models.ImageField(blank=True, upload_to='upload/sites/orther_logo/')),
                ('opposite_logo', models.ImageField(blank=True, upload_to='upload/sites/opposite_logo/')),
                ('facebook_link', models.CharField(blank=True, max_length=200, null=True)),
                ('instagram_link', models.CharField(blank=True, max_length=200, null=True)),
                ('linkedin_link', models.CharField(blank=True, max_length=200, null=True)),
                ('twitter_link', models.CharField(blank=True, max_length=200, null=True)),
                ('pinterest_link', models.CharField(blank=True, max_length=200, null=True)),
                ('map_link', models.CharField(blank=True, max_length=800, null=True)),
                ('about_data', models.TextField(blank=True)),
                ('vision_data', models.TextField(blank=True)),
                ('mission_data', models.TextField(blank=True)),
                ('termsandcondition', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('site_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='default.website')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('short_details', models.CharField(blank=True, max_length=800)),
                ('full_details', models.TextField(blank=True)),
                ('product_image', models.ImageField(blank=True, upload_to='upload/product/image/')),
                ('meta_data', models.CharField(blank=True, max_length=255)),
                ('meta_image', models.ImageField(blank=True, upload_to='upload/product/meta_image/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('category_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='default.category')),
                ('site_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='default.website')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryType',
            fields=[
                ('categorytype_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('seo_url', models.CharField(max_length=255, unique=True)),
                ('categorytype_image', models.ImageField(blank=True, upload_to='upload/categorytype/image/')),
                ('is_active', models.BooleanField(default=True)),
                ('site_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='default.website')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='categorytype_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='default.categorytype'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='default.category'),
        ),
        migrations.AddField(
            model_name='category',
            name='site_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='default.website'),
        ),
    ]
